wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = (
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("random", views.random, name="random"),
    path("<str:entry>", views.entry, name="entry"),
    path("<str:entry>/edit", views.edit, name="edit")


)

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import secrets

from django import forms
from django.shortcuts import render
from markdown2 import Markdown
from . import util

#ENTRY PAGE
def entry(request,entry):
    markdowner = Markdown()
    content = util.get_entry(entry)
    if content is None:
        return render(request, "encyclopedia/notfound.html", {
            "entry": entry,
            "form": SearchForm()
        })
    else:
        return render(request, "encyclopedia/entry.html", {
            "content": markdowner.convert(content),
            "entry": entry,
            "form": SearchForm()
        })

#INDEX PAGE
def index(request):
    return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form": SearchForm()
        })

#SEARCH PAGE
class SearchForm(forms.Form):
    search = forms.CharField(label="Search")

def search(request):
    if request.method == "GET":
        markdowner = Markdown()
        form = SearchForm(request.GET)
        if form.is_valid():
            value = form.cleaned_data["search"]
            content = util.get_entry(value)
            if content is None:
                subStringEntries = []
                for entry in util.list_entries():
                    if value.upper() in entry.upper():
                        subStringEntries.append(entry)
                        return render(request, "encyclopedia/index.html", {
                        "entries": subStringEntries,
                        "searching": True,
                        "value": value,
                        "form": form
                        })

                return render(request, "encyclopedia/notfound.html", {
                            "entry":value,
                             "form": SearchForm()
                        })
            else:
                return render(request, "encyclopedia/search.html", {
                    "entry": markdowner.convert(content),
                    "form": SearchForm()
                    })
        else:
            return render(request, "encyclopedia/index.html", {
                "form": form
            })



#NEW ENTRY PAGE
class NewEntryForm(forms.Form):
    title = forms.CharField(label="Entry", widget=forms.TextInput(attrs={'class': 'form-control col-md-8 col-lg-g'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-md-8 col-lg-8','rows':10}))
    edit = forms.BooleanField(initial=False, widget=forms.HiddenInput(), required=False)


def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            markdowner = Markdown()
            title = form.cleaned_data["title"].capitalize()
            content = form.cleaned_data["content"]
            if(util.get_entry(title) is None or form.cleaned_data["edit"] is True ):
                util.save_entry(title,content)
                return render(request, "encyclopedia/entry.html", {
                    "content": markdowner.convert(content),
                    "form":SearchForm()
                })
            else:
                return render(request, "encyclopedia/new.html", {
                        "form2": form,
                        "entry_exists": True,
                        "entry": title,
                        "form": SearchForm()
                })
        else:
            return render(request, "encyclopedia/new.html", {
            "form2": form,
            "entry_exists": False,
            "form": SearchForm()
            })
    else:
        return render(request, "encyclopedia/new.html", {
        "form2": NewEntryForm(),
        "form": SearchForm()
        })

#EDIT ENTRY PAGE
def edit(request, entry):
    content = util.get_entry(entry)
    if content is None:
        return render(request, "encyclopedia/notfound.html", {
            "entry":entry,
            "form": SearchForm()
        })
    else:
        form = NewEntryForm()
        form.fields["title"].initial = entry
        form.fields["content"].initial = content
        form.fields["edit"].initial = True
        return render(request, "encyclopedia/new.html", {
            "form2":form,
            "form": SearchForm(),
            "edit":form.fields["edit"].initial,
            "entry": form.fields["title"].initial

        })
#RANDOM PAGE
def random(request):
    markdowner = Markdown()
    entries = util.list_entries()
    random = secrets.choice(entries)
    content = util.get_entry(random)
    return render(request, "encyclopedia/entry.html", {
	"entry":random,
    "content": markdowner.convert(content),
    "form": SearchForm()
    })

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
{{content|safe}}

<a class="button" href="/wiki/{{entry}}/edit">Edit</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

{% if searching == True  %}
<h1>"{{ value }}" was not found!</h1>
Perhaps you meant:
{% else %}
<h1>All Pages</h1>
{% endif %}

    <ul>
        {% for title in entries %}
        <li><a href="/wiki/{{ title }}">{{ title }}</a></li>
        {% endfor %}
    </ul>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'tasks:search'%}" method="get">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'tasks:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'tasks:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'tasks:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
{% if edit%}
<h2>Edit Entry "{{ entry }}":</h2>
{% else %}
<h2>Add New Entry!</h2>
{% endif %}

{% if entry_exists %}
<div class="alert alert-danger" role="alert">
	This entry already exists! If you want to view or edit it, <a href="/wiki/{{ entry }}" class="alert-link">Click Here!</a>
</div>
<div class="alert alert-info" role="alert">
	Try a new entry name here!
</div>
{% endif %}
<br>
<div class="form-group">
	<form action="{% url 'tasks:new' %}" method="post">
	{% csrf_token %}
	{{form2.as_p}}
	<input type=submit>
	</form>
</div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
  <h1>Ops!</h1>
The entry "{{ entry }}" was not found!
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
       {{ entry|safe }}
{% endblock %}